// Kisan Alert Dashboard - Centralized Tailwind Configuration
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary-container": "#d3ac9c",
                "tertiary-container": "#105129",
                "on-tertiary-container": "#83c38f",
                "primary-fixed-dim": "#e6bead",
                "background": "#fff8f6",
                "surface-container": "#f4ecea",
                "outline": "#82746f",
                "on-background": "#1e1b1a",
                "error": "#ba1a1a",
                "on-surface": "#1e1b1a",
                "on-error": "#ffffff",
                "surface-variant": "#e9e1de",
                "on-error-container": "#93000a",
                "inverse-primary": "#e6bead",
                "secondary-fixed": "#ffddbb",
                "on-tertiary": "#ffffff",
                "primary": "#432a1e",
                "on-tertiary-fixed-variant": "#105229",
                "surface-container-lowest": "#ffffff",
                "surface-bright": "#fff8f6",
                "on-secondary-fixed": "#2b1700",
                "surface-container-low": "#faf2ef",
                "on-secondary": "#ffffff",
                "primary-fixed": "#ffdbcc",
                "surface-container-highest": "#e9e1de",
                "on-secondary-fixed-variant": "#673d00",
                "primary-container": "#5c4033",
                "outline-variant": "#d4c3bd",
                "surface": "#fff8f6",
                "tertiary-fixed": "#b0f2bb",
                "on-surface-variant": "#504440",
                "on-primary-fixed-variant": "#5c4033",
                "secondary-container": "#fead4c",
                "tertiary-fixed-dim": "#95d5a0",
                "on-primary-fixed": "#2c160b",
                "secondary-fixed-dim": "#ffb868",
                "on-secondary-container": "#704200",
                "error-container": "#ffdad6",
                "on-primary": "#ffffff",
                "inverse-surface": "#33302e",
                "on-tertiary-fixed": "#00210b",
                "inverse-on-surface": "#f7efec",
                "secondary": "#885200",
                "tertiary": "#003818",
                "surface-dim": "#e0d8d6",
                "surface-tint": "#765749",
                "surface-container-high": "#efe6e4",
                "parchment": "#F3EDE0",
                "cream": "#FBF8F1",
                "soil-brown": "#5C4033",
                "turmeric": "#D98E2F",
                "clay-red": "#A8472E",
                "rice-green": "#3D7A4D"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "card": "12px",
                "full": "9999px"
            },
            "spacing": {
                "xl": "64px",
                "md": "24px",
                "base": "4px",
                "gutter": "24px",
                "xs": "8px",
                "margin-mobile": "16px",
                "margin-desktop": "48px",
                "sm": "16px",
                "lg": "40px"
            },
            "fontFamily": {
                "headline-md": ["Space Grotesk", "sans-serif"],
                "display-lg": ["Space Grotesk", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "display-lg-mobile": ["Space Grotesk", "sans-serif"],
                "data-point-lg": ["JetBrains Mono", "monospace"],
                "label-caps": ["Space Grotesk", "sans-serif"],
                "table-data": ["JetBrains Mono", "monospace"]
            },
            "fontSize": {
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "display-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                "data-point-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
                "table-data": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
            }
        }
    }
};
